### ISSUE TITLE
Issue with Dynamic Presets API

### ISSUE THREAD

**Issue by jolantis** [fabianmichael/kirby-imageset#10]
Hi Fabian,

I run into the following issue:

If I include the Dynamic Presets API example snippet in my header snippet, without doing anything else (e.g. loading the preset), I get the following error:

```
Fatal error: Uncaught Exception: Initial presets are saved on initialization and cannot not be overridden at a later point.
```

What am I doing wrong?

For what it is worth, this is my imageset config:

```
c::set('imageset.styles.consolidate', false);
c::set('imageset.tags.image', true);
c::set('imageset.tags.image.sizes.default', 'default');
c::set('imageset.tags.image.class', 'figure-image size-{size}');
c::set('imageset.placeholder', 'triangles');
c::set('imageset.noscript', true);
c::set('imageset.lazyload', true);

c::set('imageset.presets', [
	'default' => [
		[ '300-2880,5' ],
	],
	'1of2' => [
		[ '320-1440,3' ],
	],
	'1of3' => [
		[ '320-960,2' ],
	],
	'hero' => [
		[ '320x180-1920x1080,5', 'media' => '(min-aspect-ratio: 3/2)' ],
		[ '320x320-1000x1000,5' ],
	],
]);
```

Any idea?

**Comment by fabianmichael** [comment]
This issue is caused, when you try to save a set of presets with the name `initial`, because it’s used internally by the plugin to save the *initial* presets defined in the config.php file. Try to use another name. But if that is an issue for you, I can change the logic, so the name initial is no longer reserved.

**Comment by jolantis** [comment]
As far as I know I am not using the name `initial` for a any set of presets?

This is the contents of the `imageset-presets.php` snippet I am using (just like your example):

```
imageset::presets([
  'default' => '200-1000,5',
  'small'   => '150-500',
  'square'  => '200x200-1000x1000,4',
]);

imageset::presets('save', 'content');
imageset::presets('reset');

imageset::presets([
  'default' => '200-500',
  'small'   => '100,150,200',
]);

imageset::presets('save', 'sidebar');
imageset::presets('reset');
```

**Comment by jolantis** [comment]
Hi Fabian,

Sorry to bother you about this issue I am having, but I just don't get it running. What am I doing wrong?

My test template looks like this:

```
<?php snippet('html-head')); ?>

	<?php snippet('imageset-presets.php'); ?>
	<?php snippet('banner'); ?>

	<main role="main" class="copy">

		<h1><?php echo $page->title()->smartypants()->widont(); ?></h1>

		<?php imageset::presets('load', 'content'); ?>
		<?php echo $page->intro()->kirbytext(); ?>
		<?php echo $page->text()->kirbytext(); ?>
		<?php imageset::presets('reset'); ?>

	</main>

<?php snippet('footer'); ?>
```

And the included `imageset-presets.php` is the one I posted in my previous post above.

And this is the error I get:

<img width="1566" alt="imageset-dynamic-api-issue" src="https://cloud.githubusercontent.com/assets/68627/24242667/bfcafa74-0fb8-11e7-9e74-9d8bdc664b88.png">

**Comment by fabianmichael** [comment]
Hey @jolantis, this was apparently just a little stup bug that made into the final release. Sorry for the invionvenience you experienced.

Best,
Fabian

**Comment by jolantis** [comment]
Thanks @fabianmichael for the quick support and fix.

Now everything is working for me. The testing is over. Now it's time to implement imagekit and imageset.

Thanks for these 2 amazing plugins!
