### ISSUE TITLE
Small images lead to fatal error

### ISSUE THREAD

**Issue by jakobploens** [fabianmichael/kirby-imageset#13]
This issue has cost me several hours yesterday of trial and error, and fortunately I was able to find the reason and find a way around – but I'd love to see a fix (or a official recommended solution for this one). To be honest: I only tried with the color placeholder, but as I don't want to use the other effects, this somehow had to work ;-) Oh, and I'm using the modules and the patterns plugins (just to mention the important things), running locally with MAMP and PHP 7.1, and all necessary things installed. Everything else is basically the default configuration from Kirby or the plugins.

After installing the plugin, the first two images worked perfectly without any problems. With the third implementation and call of `imageset()`, I got the following error:

> Method Kirby\Plugins\ImageSet\ImageSet::__toString() must not throw an exception, caught InvalidArgumentException: Passed variable is not a valid image source

Digging deeper into the code, I found out that `hasTransparency()` function triggered this error. The problem seems to be that the given `$media` object was corrupt, returning a `root = NULL` and stuff like that, while giving me the correct file URL.

After this I thought that my files where corrupt and tried the third implementation, where the error occured, with the files from instances 1 and 2. Worked like a charm. So I re-saved the original third image with Photoshop and re-uploaded it – resulting in a fatal error.

I then compared both debug info's from the `File` class, without any noticeable differences (besides path and name, of course) – and the dimensions: the first image was a hero, the second one a news preview from the old website I'm now rebuilding with 250x125px. After enlarging the image to 1000x500px, the error was gone and everything worked perfectly! But of course is not a reliable way of getting the error done – this site has only ~100 of such small images, but researching for the original images (if they still exist) and reuploading every image would cost me hours. Not speaking of sites with much more images…

In the end, I'm not really sure where the issue is coming from in the code, but to be honest, I'm not really motivated to search any further ;) It is definitely not related to the presets or sizes – I set them to '50,100' after finding out that the issue is related to the image dimensions…

**Comment by fabianmichael** [comment]
Sorry for the late reply. I tried ImageSet with a range of very small images and could not replicate your error. I will upload a beta of a new version within the next days. Maybe you could try with your again after the release or send me those files plus your imageset configuration?

**Comment by jakobploens** [comment]
Yep, seems to be fixed. Thank you!
