### ISSUE TITLE
Images aren't loaded properly

### ISSUE THREAD

**Issue by jakobploens** [fabianmichael/kirby-imageset#15]
After playing more and more with Imageset I'm quite impressed by it's possibilites – great work so far :) However, it seems that my images are sometimes lacking the `load` event and therefore just the color is displayed… I'm not quite sure where and why this takes place, but all I can say is that it's only sometimes on initial load (after reloading, it works), and also only affecting images which are over the fold, so visible on initial load. I didn't encounter this when just using lazysizes, so I guess this has something to do with the Imageset JS?

Seen in the latest versions of Safari, Chrome and FF (Dev and normal version), placeholder style is color.

**Comment by jakobploens** [comment]
One further note: the `is-loaded` class is not added to `span.imageset`, therefore the image stays invisible, but actually is loaded. A quick'n'dirty fix would be to add a z-index of 3 to the `lazyloaded` image, but then there is not transition animation visible without changing/adding much styles.

**Comment by fabianmichael** [comment]
I guess, I accidently moved initialization to a function that is executed when the DOM is ready. As lazysizes initializes earlier, this might cause the issue. I’m on it!

**Comment by fabianmichael** [comment]
Okay, ImageSet now initializes as soon as the code is interpreted and does not wait for the DOM anymore. Please try if that fixes your error, just check out the latest version of the repo. If this fixes your error, I’ll make it an official release.

**Comment by jakobploens** [comment]
Just quickly played with it, seems like the update does the job. Thanks! :)
