### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by schnti** [fabianmichael/kirby-imageset#16]
```
<?= js('assets/plugins/imageset/js/dist/imageset.js') ?>
```
Throws this error:
`Uncaught SyntaxError: Unexpected token :`
![screenshot 2017-06-17 10 39 08](https://user-images.githubusercontent.com/1868482/27251535-3752b8b0-5349-11e7-9da1-510decf24629.png)

And 
```
<?= js('assets/plugins/imageset/js/dist/imageset.min.js') ?>
```
Throws this error `imageset.min.js:22`:
```
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Object.r [as canvasRGB] (http://localhost/assets/plugins/imageset/js/dist/imageset.min.js:22:1806)
    at http://localhost/assets/plugins/imageset/js/dist/imageset.min.js:22:6440
    at e (http://localhost/assets/plugins/imageset/js/dist/imageset.min.js:22:4066)
```

**Comment by fabianmichael** [comment]
Please tell me a bit more about your setup:

- PHP version
- ImageKit & ImageSet version
- Did you get any errors in the network tab?
- Browser and OS version. Also: Does this error occur in other browsers at well?

**Comment by schnti** [comment]
Toolkit Version: 2.4.1
Kirby Version: 2.4.1
Panel Version: 2.4.1

PHP: 7.1.1 (MAMP Pro, Mac)

Chrome Version 59.0.3071.86 (Official Build) (64-bit)
Safari Version 10.1.1
Firefox Version 52.0.2 (64-bit)

ImageKit: 1.1.3
ImageSet: 1.0.1

I've found that the error only occurs in combination with Bootstrap Carousel
http://getbootstrap.com/javascript/#carousel


```
<?php

// Transform the comma-separated list of filenames into a file collection
$filenames = $data->headerImages()->split(',');

// to get with "call_user_func_array" an "Files Object" and not an "File Object"
if (count($filenames) < 2) {
	$filenames = array_pad($filenames, 2, '');
}

$items = call_user_func_array(array($data->files(), 'find'), $filenames);

if ($items->count() > 0): ?>

	<div id="headerImages-<?= $data->hash(); ?>" class="carousel slide" data-ride="carousel">

		<?php $index = 0; ?>
		<?php $first = $items->first(); ?>

		<?php if ($items->count() > 1): ?>
			<!-- Indicators -->
			<ol class="carousel-indicators hidden-xs">
				<?php foreach ($items as $item): ?>
					<li data-target="#headerImages-<?= $data->hash(); ?>" data-slide-to="<?= $index++; ?>" class="<?php e($item == $first, 'active'); ?>"></li>
				<?php endforeach; ?>
			</ol>
		<?php endif; ?>

		<div class="carousel-inner">

			<?php foreach ($items as $item): ?>
				<div class="item <?php e($item == $first, 'active'); ?>">

					<?= $item->imageset('carousel'); ?>

					<?php if ($item->caption() != ''): ?>
						<div class="carousel-caption">
							<?= $item->caption()->kirbytext(); ?>
						</div>
					<?php endif; ?>
				</div>
			<?php endforeach; ?>

		</div>


		<?php if ($items->count() > 1): ?>
			<!-- Controls -->
			<a class="left carousel-control hidden-xs" href="#headerImages-<?= $data->hash(); ?>" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="right carousel-control hidden-xs" href="#headerImages-<?= $data->hash(); ?>" role="button" data-slide="next">
				<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		<?php endif; ?>

	</div>
<?php endif; ?>
```

**Comment by fabianmichael** [comment]
Does the carousel also throw and error or adds classes or changes any other attributes on imageset tags? This is possibly related to the caroussel’s behavior, if it does not occur alone. The strangest thing is of course the syntax error, as line 474 of imageset.js does not contain a colon. Is the file transmitted properly or is it scrumbled somehow?

**Comment by schnti** [comment]
Here is a (not) working example: http://neu.bodenseehof.de which throws the error.

**Comment by fabianmichael** [comment]
I am getting a different error (`IndexSizeError: Index or size is negative or greater than the allowed amount`), but anyway we’re getting closer to the issue. It seems to be somewhere in the thumbnail rendering process. Could you please exchange the minified version of `imageset.js` on your page with the unminified one? This would make debugging much easier for me.

Also, try to use a different placeholder style and see, if the issue also affects other placeholder styles.

Thanks for your help!

**Comment by daybugging** [comment]
```php
<?php if($page->hasImages()) : ?>
  <div class="gallery">
    <?php
      $pageImages = $page->images();
      foreach ($pageImages as $image) :
    ?>
    <a class="gallery__item" href="<?= $image->url() ?>" data-caption="<?= $image->img_title() ?>">
      <?= $image->imageset([
          '150x150',
        ], [
          'placeholder' => false,
        ]);
      ?>
    </a>
    <?php endforeach ?>
  </div>
<?php endif ?>
```

Depending on value for `placeholder`, I get these errors (and on some pages no thumbs as well, see description of last point):

**triangles**
IndexSizeError: Index or size is negative or greater than the allowed amount
triangleMosaicFilter http://localhost:4000/site/plugins/imageset/assets/js/dist/imageset.js:985:29
process http://localhost:4000/site/plugins/imageset/assets/js/dist/imageset.js:1201:9
imageLoaded http://localhost:4000/site/plugins/imageset/assets/js/dist/imageset.js:710:7
placeholderRenderer.triangles/< http://localhost:4000/site/plugins/imageset/assets/js/dist/imageset.js:1208:9
loop http://localhost:4000/site/plugins/imageset/assets/js/dist/imageset.js:725:7

**lqip / blurred**
ReferenceError: el is not defined[Learn More]  imageset.js:945:13
process http://localhost:4000/site/plugins/imageset/assets/js/dist/imageset.js:945:13
imageLoaded http://localhost:4000/site/plugins/imageset/assets/js/dist/imageset.js:710:7
applyPlaceholderBlur/< http://localhost:4000/site/plugins/imageset/assets/js/dist/imageset.js:964:9
loop http://localhost:4000/site/plugins/imageset/assets/js/dist/imageset.js:725:7

**mosaic**
Method Kirby\Plugins\ImageSet\ImageSet::__toString() must not throw an exception, caught Error: Call to undefined function Kirby\Plugins\ImageSet\Placeholder\imagecreatefromgif()

**color / false**
no console error, but also no (visible) thumbnail. they get created, but don't show (seems CSS-related):
```css
.imageset.-ratio .imageset-element {
  position: absolute; /* because of this */
}
```

**Comment by fabianmichael** [comment]
@daybugging Thanks for details explanation of the errors you are getting.

I noticed that there are some issues with the latest beta. I’ll test again with my test setup. I also noticed that with asynchronuous placeholder rendering enabled, errors may occur when an imageset was removed from the DOM while the placeholder was rendering, causing the render function to fail. Though the latter one is not really problematic, because it does not cause anything else to fail, it should be handled.

I bet, your CSS example is not causing the problem of disappearing images, as the `.imageset` element has `position: relative` if it contains a ratio placeholder.

**Comment by S1SYPHOS** [comment]
I received the same error, and very rarely also this:
```
TypeError: source.parentNode is null[Learn More]  imageset.js:1202:9
  process http://dev.local/assets/plugins/imageset/js/dist/imageset.js:1202:9
  imageLoaded http://dev.local/assets/plugins/imageset/js/dist/imageset.js:710:7
  placeholderRenderer.triangles/< http://dev.local/assets/plugins/imageset/js/dist/imageset.js:1208:9
  loop http://dev.local/assets/plugins/imageset/js/dist/imageset.js:725:7
```

**Comment by fabianmichael** [comment]
@S1SYPHOS @schnti I just uploaded 1.1.0-beta2, which is a huge JS rewrite. Please try again to tee your error persists. If not, we can close this ticket.
