### ISSUE TITLE
Placeholder is not removed in rare cases when lazyloading

### ISSUE THREAD

**Issue by wottpal** [fabianmichael/kirby-imageset#18]
I used your beautiful placeholders before but I came across an issue (could reproduce it in latest firefox, but not chrome/safari) where they just not disappear even though the image has loaded long before. This is certainly the case for images which are already in the viewport when the site loads (see the video below). 

I inspected the elements and saw that the ".is-loaded" class is not appended to the lazily loaded image-wrappers (<span>'s), so the placeholder won't disappear.

This happens not every time so I had to reload multiple times in the video before it breaks. But it happens so regularly (and client has also noticed) that I had to remove the placeholders from some of my live projects :(

Screenrecording: https://www.dropbox.com/s/dz3bnhlx7589wwl/ImageSet%20Lazyload%20Issue.mp4?dl=0

**Comment by fabianmichael** [comment]
Okay, I’ll have a look at it. Will take a few days, but I already tried to improve image loading in HEAD, will probably have another look at [imagesloaded](https://github.com/desandro/imagesloaded) by desandro to see, how he does it in a more reliable way.

**Comment by ghost** [comment]
> This is certainly the case for images which are already in the viewport when the site loads

I can confirm this issue, only happens to images already in the viewport. Tested on a Moto G2, ~~never have this issue in chrome so far.~~

**Comment by fabianmichael** [comment]
What browser runs on the Moto G2?

**Comment by ghost** [comment]
Oh, of course it was Google Chrome!

**Comment by fabianmichael** [comment]
Okay, do you know if there are any differences to the desktop version of Chrome? Unfortunately, I don’t own any Android devices to test on real hardware …

**Comment by ghost** [comment]
I don't think so, also have this issue at chrome (desktop) a few times now.

**Comment by fabianmichael** [comment]
Okay, I gonna test this on Desktop then. There’s still some work to do for 1.1.0 final on the JS side anyway …
