### ISSUE TITLE
Update to lazysizes 4 once it is released.

### ISSUE THREAD

**Issue by fabianmichael** [fabianmichael/kirby-imageset#22]
Update to the latest version of lazysizes after testing thorough.

https://github.com/aFarkas/lazysizes

**Comment by S1SYPHOS** [comment]
Released two days ago, I tested it locally and didn't encounter any problem so far!

// Update:
I know you're planning a bigger rewrite by the time Kirby 3 is released, however, would you accept a PR for lazysizes v4.0.1 support? I'd be happy to help :statue_of_liberty:
