### ISSUE TITLE
Throws error on completely transparent PNG

### ISSUE THREAD

**Issue by wottpal** [fabianmichael/kirby-imageset#23]
:D This is a funny one i stumbled across accidentally: ImageSet throws an exception when the input image is an completely transparent .png.
![bildschirmfoto 2017-08-07 um 22 54 38](https://user-images.githubusercontent.com/3930150/29045312-72833dcc-7bc3-11e7-9ce2-0e0fe4a2ab84.png)

**Comment by fabianmichael** [comment]
Alright, I did not test this special case to be honest … but it should be fixed anyway, especially for sites displaying experimental invisible art! :-D
