### ISSUE TITLE
Ignore GIF

### ISSUE THREAD

**Issue by guidoferreyra** [fabianmichael/kirby-imageset#24]
Is possible to make ImageSet ignore gifs? Because it eliminates the animation.

**Comment by fabianmichael** [comment]
Unfortunately not, you have to handle this either in your templates or if you need this in Kirbytext, you should override ImageSet’s `(image: …)` Kirbytag if you don’t want GIF images to be resized. 

BTW: ImageSet just uses Kirby’s built-in thumbs engine, so if you want resized versions of animated GIF images, you would have to tweak Kirby’s thumb driver.

**Comment by fabianmichael** [comment]
However, I think it would make sense to add a setting for handling of GIF files.
