### ISSUE TITLE
Uncaught ReferenceError: el is not defined

### ISSUE THREAD

**Issue by ghost** [fabianmichael/kirby-imageset#25]
````
imageset.js:945 Uncaught ReferenceError: el is not defined
    at process (imageset.js:945)
    at imageLoaded (imageset.js:710)
    at imageset.js:964
    at loop (imageset.js:725)
````

Using the latest imageset version. I tried to replace `el` with `wrapper` after looking through the commit history. I think the problem started with the latest refactoring and kugugug 😹 I switched back to 1.0.1, didn't try it with other effects than blurred/LQIP.

**Comment by fabianmichael** [comment]
The current version on git seems to have a typo in a variable name. I’m on it!

Which placeholder style are you using? It affects `blurred` and `lqip`.

**Comment by fabianmichael** [comment]
@glumanda99 FYI: I just uploaded 1.1.0-beta2. Please let me now if your error persists. Otherweise, I will close this ticket soon cb36c2c4718f7ad5bb60893e038c91bff847d1b6.
