### ISSUE TITLE
Using ImageSet with Asset objects

### ISSUE THREAD

**Issue by S1SYPHOS** [fabianmichael/kirby-imageset#27]
Congratulations to 100 ⭐️ 
Question: Is there any way to use it with Asset objects (see [docs](https://getkirby.com/docs/templates/thumbnails))?

When I do this:
```php
$fallback = new Asset('assets/images/header.jpg');
echo $fallback->imageset([ '900x243' ], [
  'placeholder' => 'triangles',
  'alt' => $image->img_desc()
]);
```
.. I get `Call to undefined method Asset::imageset()`. It seems to be similar to #4.

**Comment by S1SYPHOS** [comment]
Should've read more closely, `echo imageset($fallback, '...')` did the trick ..

**Comment by fabianmichael** [comment]
Wow, I missed that my little plugin already has 100 stars :-D

I would really like to add the imageset method to the Assets class as well. But in contrast to the `File` class, it currently does not offer the possibility to register custom methods. So for now, we’re stuck with using `imageset()` for now.
