### ISSUE TITLE
Thumbnails blacking out during lazyload

### ISSUE THREAD

**Issue by S1SYPHOS** [fabianmichael/kirby-imageset#28]
Hey there,
until #16 is fixed I'm using v1.0.1 and stumbled across the behaviour described in the title:

![black-out](https://user-images.githubusercontent.com/12161504/31094840-cdac89a0-a7b6-11e7-8faa-60d01c05fcc6.gif)

Upon page load, sometimes there's a black-out of some thumbnails generated by ImageSet. I checked if this was fixed in the most recent beta release but didn't find anything.

**Comment by fabianmichael** [comment]
@S1SYPHOS Hey there, finally I’m catching up … does you issue still exist (could also be a rendering bug in the browser engine. In that particular case, it would be out of my possibilities to control it)? Please try again with `1.1.0-beta2`.

**Comment by S1SYPHOS** [comment]
Will try & get back at you.
