### ISSUE TITLE
FocusCrop and Imageset

### ISSUE THREAD

**Issue by ChrisKam** [fabianmichael/kirby-imageset#30]
Hi there, first of all thank you for the great plugin!

I'm having the exact same issue as oliverschneider describes here: https://forum.getkirby.com/t/imageset-responsive-images-with-lazy-loading-and-beautiful-placeholders/6006/28

However, I *should* have come farther I thought by doing this

`  $image = $image->focusCrop(800); // making it an Asset Object btw.`
`  $image = new Media($image->root());`
`  echo $image->imageset('400-800');  `

... but no such luck "Call to undefined method Media::imageset()" - which is extra odd since imageset should support not only File, but Media Objects I believe. Neither does it work with an Asset object although the source suggest that Media Object get converted to Asset Objects in any case ;-)

Any help would be super appreciated!

**Comment by fabianmichael** [comment]
Hi @ChrisKam, unfortunately the Media object cannot be extended. If you look into Kirby’s source, you’ll notice the the Media and Asset classes are not extensible like the File class (you can add custom methods to the File object by using sth. like `file::$methods['imageset'] = function() { […] };`). I’m afraid, there’s nothing I can do here. but you can always create imagesets by passing a `Media` object to the `imageset($media[, options])` helper function.
