### ISSUE TITLE
readme js file

### ISSUE THREAD

**Issue by bnomei** [fabianmichael/kirby-imageset#31]
about **2.3 template setup** of readme... should be minified file, right? its currently not.

```php
<?= js('assets/plugins/imageset/js/dist/imageset.min.js') ?>
```

**Comment by fabianmichael** [comment]
@bnomei I added the uncrompressed file with dev environments in mind. Do you think, the minified version would make more sense? I guessed that most devs would include it in their build process anyway to have a single JS payload for production …

**Comment by bnomei** [comment]
i did add the minified script to my [loadjs](https://github.com/muicss/loadjs) chain so i can use whatever version your plugin provides – keeping plugin code separated from website code. no webpack merge etc.
you could add a note [here](https://github.com/fabianmichael/kirby-imageset#23-template-setup) that a minified version is available as well.

**Comment by fabianmichael** [comment]
Replaced with minified file in cb36c2c4718f7ad5bb60893e038c91bff847d1b6.
