### ISSUE TITLE
JS Error in the console

### ISSUE THREAD

**Issue by wottpal** [fabianmichael/kirby-imageset#32]
Hey,
I am using the latest version of ImageSet and getting this error in the console recently `Uncaught ReferenceError: el is not defined` on line **945** of `imageset.js`. Maybe you could have a look :)

Btw are you planning future releases of ImageSet & ImageKit? Both seem a bit stagnant unfortunately :(

Dennis

**Comment by fabianmichael** [comment]
Hi Dennis,

sorry that I've been kind of idle regarding the work on my plugins. I’ve been drowning in client work over the last month (I’m alright, if you’re asking …). I will start to develop major new versions for Kirby 3 once it’s in a state where development of comprehensive plugins makes sense.

Bugs however should be fixed, especially as the frontend code of ImageSet has basically nothing to do with Kirby and could be used with an backend that spits out the right HTML. I hope to have some time available for fixing ImageSet’s remaining bugs soon.

Best,
Fabian

**Comment by wottpal** [comment]
Hey Fabian :)
I can totally understand your situation, hope you have some more time soon!
Nonetheless many of my sites rely on ImageSet & ImageKit and I somehow thought the paid license model ensures its reliability at least for a while. I'm also very hyped for Kirby 3 but I'm definitely not planning to upgrade all of my sites immediately (or even at all) so if you plan to focus on Kirby 3 versions please don't forget Kirby 2 (at least with bugfixes)!

**Comment by fabianmichael** [comment]
@wottpal Just released 1.1.0 Beta 2 :-) Please try agaign if your issue is fixed by now (I really hope so).

**Comment by wottpal** [comment]
It seems to be fixed. Thanks! :)
