### ISSUE TITLE
lozad.js

### ISSUE THREAD

**Issue by bnomei** [fabianmichael/kirby-imageset#33]
you might wanna check out this lib as an alternative to **lazysizes**. or maybe support both? or if one is already loaded?

https://apoorv.pro/lozad.js/

**Comment by fabianmichael** [comment]
It looks pretty interesting and lean, but sorry I don’t see a chance to replace lazysizes in the near future. In comparision to most other solutions, lazysizes can dynamically detect the actual width of an image and thus automatically calculate the `sizes` attribute.

However, I’m planning for a bigger rewrite when Kirby 3 is released. Maybe I’ll find the time to make a deeper comparison between those 2 scripts. There is also the problem of the intersection observer polyfill dependency for older browsers. This would mean that users would have to add another conditional script tag to their site or the polyfill has to be loaded for all users. Don’t get me wrong, I think that inersection observer is a great API, but a change that requires a new embed code for the plugin should not happen in a minor update. But I am leaving this ticket open as an idea, maybe lozad is sth. for version 2. ;-)
