### ISSUE TITLE
Whitespace at bottom of images

### ISSUE THREAD

**Issue by azharc** [fabianmichael/kirby-imageset#34]
The span.imageset element has a little whitespace below the image. I don't believe I have other styles causing this, but feel free to close/ignore if you can't replicate. 

In case you can, here's how I fixed it. 

![1](https://user-images.githubusercontent.com/2773389/35078502-89d8902a-fbd0-11e7-9817-9a72e7896374.png)
![2](https://user-images.githubusercontent.com/2773389/35078503-89f592d8-fbd0-11e7-973c-f60987e33319.png)

**Comment by azharc** [comment]
Setting display:flex to the span.imageset element also works as a fix.

**Comment by fabianmichael** [comment]
Can you give me access to a demo, so I can check where the issues comes from?

In general, as `.imageset` is displayed as `inline-block` to behave like a normal image. I never tested with `display: flex`, but you can also safely use `display: block` on the `.imageset` element if you want to get rid of bottom whitespace.

**Comment by fabianmichael** [comment]
https://github.com/fabianmichael/kirby-imageset/issues/35

**Comment by fabianmichael** [comment]
Notice for setting `display: block` has been added to readme in cb36c2c4718f7ad5bb60893e038c91bff847d1b6
