### ISSUE TITLE
Integrating imageset.js in my workflow

### ISSUE THREAD

**Issue by daybugging** [fabianmichael/kirby-imageset#38]
Hey there,
quick question: I want to include imageset.js in my own workflow (currently webpack), how would I go about this? Importing the library (`import 'path/to/plugin/imageset.js'`) works, but then execution fails.

Tested this with the latest version of ImageSet, any pointer is much appreciated!
Thank you.

**Comment by fabianmichael** [comment]
Hey @daybugging,

sorry that it took a while … I just uploaded `1.1.0-beta2`, which is a huge JS-rewrite. Please try again with the latest version and see if your problems persists.

Best,
Fabian
