### ISSUE TITLE
Security vulnerability in build process

### ISSUE THREAD

**Issue by colly** [fabianmichael/kirby-imageset#41]
Hi there,

For a couple of weeks, Github has been giving me the following warning relating to the use of the Imageset plugin 1.1.0-beta2 on my Kirby build (now updated to 2.5.11).

<img width="777" alt="screenshot 2018-07-03 11 33 32" src="https://user-images.githubusercontent.com/867489/42215070-424dd1f8-7eb5-11e8-8841-13daf633ec4f.png">

<img width="733" alt="screenshot 2018-07-03 11 34 02" src="https://user-images.githubusercontent.com/867489/42215083-49de27f6-7eb5-11e8-9e8c-9c861a865f33.png">

I was hoping you'd have fixed this but maybe you didn't see; perhaps now it's right I draw your attention to it. I really need Imageset in my forthcoming build; all of my image work relies on it, and this issue is beyond my skillset.

Thanks,

Simon Collison

**Comment by fabianmichael** [comment]
Hi @colly,

I ran a quick `npm audit` within the repo to investigate this. As far as I can tell (`node_modules/` is said to contain more modules than there are particles in the whole universe) this is a dependency used by **node-sass** in the build process and nothing that is nothing that should affect the actual frontend code. From a security point of view, it should be safe to use ImageSet. However, I’ll update the dependencies with the next release.

Cheers,
Fabian

**Comment by colly** [comment]
Great. Thanks for the clarity, and for continued maintenance of the plugin.
