### ISSUE TITLE
Saturation issues

### ISSUE THREAD

**Issue by foopz** [fabianmichael/kirby-imageset#43]
Thank you for the fantastic plugin my pages load so gracefully now.

I have noticed a slight issue with image saturation/vividness of colors are. It seems imageset is making the slightly muted as you can see in the attached thumbnail. I'm not sure whether this is a bug or bad implementation of the plugin by me. Any help would be greatly appreciated. 

![imageset_saturation](https://user-images.githubusercontent.com/40631517/44936782-fa77dd00-ad6d-11e8-94c4-dbe48fa36c7f.jpg)

Template Code
```
<div>
    <div>Imageset</div>
    <?php if($image = $page->thumbnail()->toFile()):?>
        <?= $image->imageset([
                '160-1280,6', 'sizes' => '(min-width: 640px) 100vw, 50vw'
            ], [
                'class'       => 'awesome-image',
                'placeholder' => 'color',
            ]) ?> 	  
    <?php endif; ?>
</div>
<div>
    <div>Default</div>
    <?php if($image = $page->thumbnail()->toFile()):?>
        <img style="width: 100%;" src="<?= $image->url() ?>" />
    <?php endif; ?>
</div>
```

**Comment by foxacid** [comment]
This looks like a color space issue. Can you compare the color profiles of your source and thumbnail images? Try to convert your source image to sRGB and see if that fixes it...

**Comment by fabianmichael** [comment]
Hi, the color change is probably happening inside of Kirby’s thumb driver (which ImageSet is relying on). As far as I know, the default driver does not preserve color profiles. The best way to get around this issue, is probably to override the built-in driver with a custom solution bases on ImageMagick, as it offers more options than GD:

Source code:
https://github.com/getkirby/kirby/blob/master/vendor/getkirby/toolkit/lib/thumb.php#L272

Tutorial for writing custom thumb drivers:
https://getkirby.com/docs/developer-guide/toolkit/thumb-driver

Docs for ImageMagick:
https://www.imagemagick.org/script/command-line-options.php

**Comment by foopz** [comment]
Thank you so much for the help. Following @foxacid's advice I was able to determine that the problem is the lack of an sRGB color profile. Following the the links of @fabianmichael it seems it's as simple as copying the template of Imagemagick to a custom driver, adding the line:

```
$command[] = '-colorspace sRGB';
```
And then setting `c::set('thumbs.driver', 'pd');` in the config. However, the colors are still muted when the thumbnail is made. Is there something I am missing?

edit

Adding `$command[] = '-profile sRGB.icc';` does not seem to make a difference either. Ideally I would like to automate the conversion of the images from RGB to sRGB so that the user does not have to do this in photoshop before uploading.
