### ISSUE TITLE
How to add an HTML attribute to the img tag

### ISSUE THREAD

**Issue by krlklm** [fabianmichael/kirby-imageset#44]
I try to use imageset for an image map. I would need to add `usemap="#imagemap"` within the `<img>` tag. Is this possible, and if, how? Thanks!

Well, i just learned that image maps don't scale, because they are pixel based. So i will have to check how i can build a responsive image map equivalent with SVG. I will post here again if i still need this functionality.

**Comment by fabianmichael** [comment]
Okay, good luck with finding a working solution, but SVG sounds like a good plan to me.

Can I close the ticket?

**Comment by krlklm** [comment]
Yes, i found a solution with SVG based on this [blog post](https://patrickkettner.com/posts/responsive-image-maps/) by Patrick Kettner. Thanks!
