### ISSUE TITLE
Ignore some images in (image: …) kirbytag

### ISSUE THREAD

**Issue by jklue** [fabianmichael/kirby-imageset#45]
Is there a way to add a class to an image tag or parent container that will prevent imageset from lazy loading it or doing anything to it?

**Comment by fabianmichael** [comment]
No, this is currently not possible by using a parameter. However, you could can copy a customized version of the image tag into `site/tags` and add a parameter that allows you to disable ImageSet on certain images or even disabling it by default.

You can find the code for the image tag in https://github.com/fabianmichael/kirby-imageset/blob/master/tags/image.php

When doing this, you should add `c::set('imageset.tags.image', false)` to your config.php.

But as I think, this would be an excellent addition to the plugin, I woudl be happy to add this feature at some point. I’m just thinking about how these options should be named. Maybe `imageset.tags.image.default` for config and `(image: … imageset: false)` for the parameter?

**Comment by jklue** [comment]
(image: … imageset: false) would be perfect! I don't understand the use for `imageset.tags.image.default` though.

**Comment by fabianmichael** [comment]
I thought it could be handy to let the developer choose whether imageset should be opt-in or opt-out for Kirbytext, that’s was this option was supposed to be for.

**Comment by jklue** [comment]
Brilliant. In my mind it would be something like `imageset.tags.image.optional`, and if it were set to true, then the `(image: ... imageset: false)` feature would have an effect.

**Comment by jklue** [comment]
@fabianmichael this may warrant a new issue, but would it be possible to prevent imageset from running on a certain page? I'm not loading the header scripts on a certain page, but that doesn't seem to prevent it from working on the images.

**Comment by fabianmichael** [comment]
@lukehatfield This won’t work, as ImageSet generates special HTML code for lazy-loading. The plugin has no way of determing whether a certain script is loaded or not. As there are lots of different script-loading methods and build processes, it would not be feasible to attempt that.
