### ISSUE TITLE
Future K3 compatibility?

### ISSUE THREAD

**Issue by colly** [fabianmichael/kirby-imageset#46]
I noticed you updated the readme stating incompatibility with K3. I'm eager to upgrade but have imageset woven into my build. Do you have a proposed date for K3 support? I'd be willing to pay again for an update.

**Comment by fabianmichael** [comment]
Sorry, no date yet. I will start with porting ImageSet as soon, as my schedule allows it.

**Comment by rcvd** [comment]
Any updates on this? Desperately waiting for it...

**Comment by fabianmichael** [comment]
Sorry, no updates yet. My schedule might get better over the next weeks, but I cannot make any promises so far.

**Comment by scsskid** [comment]
great pluign, take your time
could you maybe provide a starting point, to extend the default (image: ) tag with a resize option, which actually resizes the provided file and keeps the existing attributes?

**Comment by fabianmichael** [comment]
I had to make the decision, to stop all development for ImageKit and ImageSet. See https://forum.getkirby.com/t/the-end-of-imagekit-and-imageset/15824 for a more detailed explanation.
