### ISSUE TITLE
Write Tutorial for PhotoSwipe integration

### ISSUE THREAD

**Issue by fabianmichael** [fabianmichael/kirby-imageset#7]
Support PhotoSwipe for enlarging images.

**Comment by krlklm** [comment]
Is there a rough time schedule when we could expect PhotoSwipe support respectively v. 1.2.0 ?

**Comment by fabianmichael** [comment]
I did an implementation for my personal site (example: https://fabianmichael.de/en/work/sister-carrie), but I’m not sure how to integrate it into the plugin. Problem is, that there’s a ton of different build processes out there and I don’t know if it’s worth to ship Photoswipe assets with ImageSet. To run photoswipe, you need to include a 2 js files, one CSS file and it also needs to load images. Plus, there’s that big chunk of HTML you have to include somewhere befor `</body>`. My guess is that most users would prefer to bundle up those assets with the rest of their assets. But I also don’t want to force users to install Photoswipe as a node module for having it available for their build processes. All in all, this can easily get very complicated, also regarding the images included with Photoswipe which are IMHO better served from the assets folder.

Maybe publishing it as a tutorial might be a better idea instead? What do you think?

**Comment by krlklm** [comment]
I guess a tutorial would actually be better than integrating it. I have to admit that i thought Photoswipe would be more or less the same as Swiper (http://idangero.us/swiper/), which i would like to combine with ImageSet. So a tutorial for one of the two would probably be more universally applicable. Thanks in advance!

**Comment by fabianmichael** [comment]
Okay, I’ll write the tutorial then.

**Comment by krlklm** [comment]
Hello. Any news on the tutorial? Thanks!

**Comment by krlklm** [comment]
I have ImageSet now working inside Swiper, so for me the tutorial is not necessary anymore.

A bit out of context, but maybe anyone can use it:

This is pulling the images from a blueprint that contains a structured field 'slider' that has a field 'image'

`<?php $slides = $data->slider()->yaml(); ?>`
` <div class="swiper-container">`
`<div class="swiper-wrapper">`
`<?php foreach($slides as $slide) : ?>`
`<div class="swiper-slide">`
`<?php if($image = $data->image($slide['image'])) {echo $image->imageset('name_of_the_imageset');} ?>`
`</div>`
`<?php endforeach ?> `
`</div>`
`</div>`

Kirby 2.5.8
ImageSet 1.0.1
Swiper 4.1.0
