### ISSUE TITLE
congrats to release 1.0 🎊

### ISSUE THREAD

**Issue by bnomei** [fabianmichael/kirby-imageset#8]

**Comment by fabianmichael** [comment]
Thanks a lot! The great feedback and interest, the plugin got in such a short timeframe show me, that it tackles real-world problems and is not just the fantasy of a designer who wants cool effects on images. Yeah … and it really took a while to take off, as I’ve been experimenting with image loading in that particular way for about 2-3 years now. Fun fact: I started this when I was still using WordPress and had the plan to make a WP plugin back then. :-D
